### ISSUE TITLE
Support utf8 domain (zone) and rrset names without punycode

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#123]
In wake of issue #108, it would be nice to have the serializer convert from utf8 to punycode and back to hide puny names from the user.

Implementation idea: https://gist.github.com/hangtwenty/8aaab82e6ba23806f8dc#file-quick_punycode_encode_decode_example-py-L31

ping @My1

**Comment by My1** [comment]
The idea is definitely great, but we have one big annoyance/problem.

which IDNA/Punycode standard do we wanna use? and whether we "help" the user (especially in IDNA2008)

https://de.wikipedia.org/wiki/Internationalisierter_Domainname#Inkompatibilitäten_von_IDNA2003_und_IDNA2008 (German)

or here a nice english text about this

https://www.plesk.com/blog/product-technology/what-is-the-problem-with-s/

in 2003 there were a few things done before Punycoding the whole thing (one relatively big thing is the auto-conversion from ß to ss), while in 2008 the whole normalisation falls mostly out of the window and with that ß gets properly converted into the puny section.

ß is not alone but there are in total 4 charcters interpreted differently:

U+00DF ( ß ) LATIN SMALL LETTER SHARP S
U+03C2 ( ς ) GREEK SMALL LETTER FINAL SIGMA 
U+200C ( ) ZERO WIDTH NON-JOINER
U+200D ( ) ZERO WIDTH JOINER

also 2008 kicks a whole lot of characters out of the window, and them we also have UTS#46 which is a completely different beast, as it tries to make the transition easier

here's BTW a nice comparison page which also allows input to check how what would look in each of the 3 Standards.

https://www.unicode.org/cldr/utility/idna.jsp

-----

*Personally* I would say to generally apply IDNA2008, with some "enhancements" to make it user-friendly.

and that the disallowed characters, which have **only one** way of interpretation (capital letters become small, fullwidth alphanum goes half, half-width kana go full, just as example) should be converted (maybe along with a warning), characters that cannot be converted either due to no (emoji for example which for a big part arent allowed in 2008) or multiple alternatives, should throw an error stating which characters are at fault.

for example: ÖBBẞｶ.tld becomes öbbßカ.tld with a warning, while ☕.tld gets only an error.

obviously after conversion the converted unicode variant should be shown instead of the input.

**Comment by nils-wisiol** [comment]
@my1, would you be able to create a PR for that functionality?

**Comment by My1** [comment]
honestly I never did Python and personally I think it would probably be easier to just say "use punycode" (especially considering this is in beta and API only so far), and especially due to the fact that the IDN support is pure chaos right now, it's better to have the user choose how they do it, at least until browsers get a consensus since otherwise there will be chaos. although I can try to make a letter mapping array to get the enhancements. for the filtering of forbidden characters it would be easy by going to Puny and back as the forbidden characters should leave an error (which would show that something is wrong) or just get axed (which can be checked by converting back and checking the result against the prepared string)

**Comment by nils-wisiol** [comment]
Alright, we may come back to this later or upon public demand
