### ISSUE TITLE
deSEC DNS Authenticator plugin for Certbot (Let's Encrypt)

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#125]
Let's write a plugin like this one: https://github.com/certbot/certbot/tree/master/certbot-dns-cloudflare

**Comment by My1** [comment]
certainly intresting but as with cloudflare the need to have the plugin have essentially the master key to the account is kinda concerning.

**Comment by peterthomassen** [comment]
Depends on implementation

**Comment by My1** [comment]
sure, implementation can change a lot but usually certbot runs directly on the web server and posts the certs into it (and if that server is broken, then the "fun" begins), and sure, one can play some very fun scenario with a server "in the back" actually obtaining the cert and pushing it into the web server so that there is no inbound access at all to the server with the master key, but I doubt many would do that.

especially when the key is the only credential to the account with not even a way to really reset it (except maybe support) it is as said concerning.

I am not saying  it's totally bad or whatever, but one should be careful with this, that is my point.

**Comment by peterthomassen** [comment]
see https://github.com/desec-io/certbot-dns-desec/

**Comment by peterthomassen** [comment]
Released at https://pypi.org/project/certbot-dns-desec/. Thanks @nils-wisiol!

Docs updates are tracked in #509.
