### ISSUE TITLE
http://update6.dedyn.$DOMAIN broken

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#339]
This bug is invisible if you have received HSTS headers on update6.dedyn.$DOMAIN. However, it's visible using curl:

    $ curl http://update6.dedyn.io
    curl: (52) Empty reply from server
    $ curl https://update6.dedyn.io
    No username URL parameter provided.

The expected behavior would be a redirect on https.

**Comment by peterthomassen** [comment]
No, that's by intention: https://github.com/desec-io/desec-stack/commit/89414527b56fa6ec0fa3cddbb4c17c20d4bee84a

We said we'll try it out and revert if problems arise. Now, one user has the problem - is that enough to justify dropping the idea of offering HTTPS only?

On the other hand, not running the HTTP redirect does not strictly help security either, since a MITM could run it. But it helps to make people think HTTPS by default.

If the problem doesn't reoccur, I'd personally vote for HTTPS only, and to tell people that they should configure their clients accordingly.

**Comment by nils-wisiol** [comment]
I guess we're not winning anything by not answering the request instead of telling the client to use HTTPS (both with HSTS and HTTP redirect). Smart clients would probably observe redirect and HSTS, dumb clients won't do neither
