### ISSUE TITLE
Changing email local part to lower case violates RFC 5321

### ISSUE THREAD

**Issue by dops7** [desec-io/desec-stack#417]
The local part must not be modified in case for storage in the database.

**Current behaviour**
After registration emails are sent to an address converted to lower case, and authentication only works with the email address in lower case, while login with the original local part is not possible.

**Standards**
RFC 5321 https://tools.ietf.org/html/rfc5321#section-2.4                                                 
"The local-part of a mailbox MUST BE treated as case sensitive."

**Proposed Change for Compliance**
1. For existing account checks compare as lower case (or more generic regarding Unicode: follow Unicode procedures for checking of equality). Justification: It is highly recommended for email providers to not assign addresses only differing in case to multiple persons.
2. Store email address local part _as is_ in the database (domain part can and should still be normalized)
3. For authentication define and implement behaviour: Either only with case provided during registration, or accept variants in different case.

**Future enhancements**
Email addresses move towards "Universal Acceptance" allowing non-latin character sets in email addresses, which can also be considered. Refer to https://uasg.tech .

**Comment by nils-wisiol** [comment]
Hi, thanks for this excellent report.

We noticed this behavior and decided that we want to allow authentication in all casings; hence did not change. I agree though that for sending email, we should use the original casing.

My proposal for this is to implement

- [ ] upon user creation, store email address as-is, put unique constraint on lower-cased variant
- [ ] when sending email, use email address as stored
- [ ] during login, compare case-insensitive
- [ ] for existing accounts, do nothing (because what could we do?)

I confirmed that the current behavior is to lower-case email addresses, however about 3% of existing accounts have non-lower case addresses stored in out database; those were created in between July 2015 and April 2020. (They also account for about 3% of the accounts created during that time; there are such accounts for each month during that time.)

Those changes would remove the possibility that "reset password" emails and such will be delivered to the wrong mailbox -- note however that the account is still bound to this wrong mailbox unless the mail server changes its opinion on which mailbox the lowercased address belongs to. I guess that's a small win in security.

Accepting case-variants on login removes the possibility of having multiple user accounts with case-variant email addresses -- who should we authenticate? (The one with the right password? 😳) One could argue a loss of security here, was email addresses can be guessed easier when we accepts all sorts of variants -- but I do not think that this is a big loss.

For Universal Acceptance, I'd gladly integrate it, but let's treat that separately from the casing issue. Otherwise, the casing may be hold back for some time. (I guess Universal Acceptance does raise some security concerns -- who knows what our libraries do with fancy email addresses and such.)

Overall, I'd be happy to accept a pull request for this!

**Comment by peterthomassen** [comment]
> Accepting case-variants on login removes the possibility of having multiple user accounts with case-variant email addresses -- who should we authenticate?

I think that's acceptable; it's hard to imagine two different but legitimate users whose email addresses only differ in casing.

**Comment by peterthomassen** [comment]
The current situation is the following:

- Our API lowercases the domain part, but not the local part. (This is the Django standard behavior for email addresses.)
- The database collation is case sensitive. As a result, the uniqueness constraint is case sensitive.
- Our GUI lowercases the email address as a whole.

As a result, users that have signed up (pre-GUI) with non-lowercase email addresses can't use the GUI to reset their password, as the address will be forced to lowercase and then not be found in the database.

What needs to change: During lookups and uniqueness constraint checks, we should ignore case.

Potential ways forward:
1. We can implement this in the API, but then we'll end up with a time-of-check / time-of-use race condition for the uniqueness constraint, and potentially will have two accounts with addresses that only differ in casing, breaking both (single-object retrieval will fail due to ambiguity).
2. A case-insensitive column collation would give us exactly what we need. (This is supported by MySQL/MariaDB, Postgres, and sqlite.)
3. We can also leave the collation as is, and add a case-insensitive uniqueness constraints on database level. (This is at least supported by MySQL/MariaDB and Postgres, sometimes requiring a virtual column.) This solution, however, will still have case-sensitive lookups.

The best option is option 2. Implementation by database system (it's may be necessary to also repeat the data type in the `ALTER TABLE` statements):
- MySQL/MariaDB: `ALTER TABLE desecapi_user MODIFY email COLLATE utf8mb4_unicode_ci;` ([justification](https://stackoverflow.com/a/766996/6867099))
- Postgres: `CREATE COLLATION "und-u-ks-level2-x-icu" (provider = icu, locale = 'und-u-ks-level2', deterministic = false); ALTER TABLE desecapi_user ALTER COLUMN email COLLATE "und-u-ks-level2-x-icu";` ([explanation](https://www.postgresql.org/docs/12/collation.html))
- SQLite: `ALTER TABLE desecapi_user MODIFY email COLLATE NOCASE;` ([possibly online allowed during table creation](https://www.sqlite.org/datatype3.html#collation))

We need SQLite for our tests, and MariaDB for our current deployment, which we may later **(or now?)** switch to Postgres.

Unfortunately, Django has no interface for setting field collations ([and I don't see it coming](https://code.djangoproject.com/ticket/5745)), so these would have to be done in a database-dependent migration. However, I don't see a better way to handle this. Thoughts?

**Comment by peterthomassen** [comment]
The correct SQL for Postgres is:

```sql
CREATE COLLATION "und-u-ks-level2-x-icu" (provider = icu, locale = 'und-u-ks-level2', deterministic = false);
DROP INDEX IF EXISTS desecapi_user_email_fa6ced42_like;  -- ID may differ
ALTER TABLE desecapi_user ALTER COLUMN email TYPE character varying(191) COLLATE "und-u-ks-level2-x-icu";
```

The `desecapi_user_email_fa6ced42_like` index needs to be dropped because it uses the `varchar_pattern_ops` operator class which is incompatible with case-insensitive collations. (More precisely, it's incompatible with nondeterministic collations in Postgres, and case-insensitive collations are nondeterministic.)

[Django may support removing the index in the future](https://code.djangoproject.com/ticket/24082), by specifying `db_index=False` on the `User.email` field. The current behavior is to ignore the flag if the field is declared unique (which it is).

**Comment by dops7** [comment]
Updated situation when collation is changed:

> The current situation is the following:
> 
>     * Our API lowercases the domain part, but not the local part. (This is the Django standard behavior for email addresses.)
Status neutral: no conflicts (lowercasing probably not necessary but allowed for the domain part)

>     * The database collation is case sensitive. As a result, the uniqueness constraint is case sensitive.
Status solved: Emails are found in the database for all consumers, no matter which case

>     * Our GUI lowercases the email address as a whole.
Status needs change: Case of the local part must be preserved

Idea for existing accounts considered as duplicate when compared in case-insensitive manner:
API and GUI could deal with multiple database query results and try to authenticate both, and maybe followed by deactivating all besides the succeding item as cleanup.

Thanks for your efforts!
