### ISSUE TITLE
Web-gui: CNAME content does not allow leading asterisk or underscore

### ISSUE THREAD

**Issue by renne** [desec-io/desec-stack#446]
When trying to create CNAME records the web-gui denies using asterisk or underscore as a leading character in the content.

Failing examples:
```
_DMARC  3600  IN  CNAME  _DMARC.example.org.
*.udp   3600  IN  CNAME  *.tcp.example.org.
```

**Comment by peterthomassen** [comment]
Thanks for the bug report!

Would you like to fix this issue? The validation regex is here: https://github.com/desec-io/desec-stack/blob/master/webapp/src/components/Field/RecordCNAME.vue

**Comment by peterthomassen** [comment]
Fixed for underscore.

What is the meaning of a wildcard target? (Which use case would it support?)

**Comment by peterthomassen** [comment]
Closing due to lack of feedback; it is possible that the reporter already is satisfied with the partial fix. Feel free to comment if that is not the case.

**Comment by andrewtj** [comment]
> What is the meaning of a wildcard target? (Which use case would it support?)

What's the value in restricting the target beyond it being a valid name?

For what it's worth a wildcard target would be more efficient on the wire as no proof of non-existence would need to be included.

**Comment by peterthomassen** [comment]
> What's the value in restricting the target beyond it being a valid name?

The question is what should be a valid name. CNAMEs are used for hostnames, and hostnames don't start with an asterisk. I'd love to learn that I'm wrong.

For the sake of completeness: DNS labels may contain arbitrary bytes, so anything would be allowed between dots (even non-printable characters). We do impose the restriction that domain names should be valid names. The point of contention here is whether a wildcard name is a valid name itself (or, rather, just a wildcard that can _match_ names).

> For what it's worth a wildcard target would be more efficient on the wire as no proof of non-existence would need to be included.

Things related to proof of non-existence depend on what record sets are defined (in terms of their names and types, "left-hand side"), but not on what their values are ("right-hand side"). Wildcards on the left-hand side are already allowed, so the suggested benefit is already there. The right-hand side, which is being discussed here, plays no role in proofs of non-existence.

**Comment by andrewtj** [comment]
> The question is what should be a valid name. CNAMEs are used to point to hostnames, and hostnames don't start with an asterisk. I'd love to learn that I'm wrong.

CNAMEs are in no way specific to host related records.

> For the sake of completeness: DNS labels may contain arbitrary bytes, so anything would be allowed between dots (even non-printable characters). We do impose the restriction that domain names should be valid names. The point of contention here is whether a wildcard name is a valid name itself (or, rather, just a wildcard that can match names).

Yes, a wildcard name is a valid name, if for no other reason than it matches itself.

> Things related to proof of non-existence depend on what record sets are defined (in terms of their names and types, "left-hand side"), but not on what their values are ("right-hand side"). Wildcards on the left-hand side are already allowed, so the suggested benefit is already there. The right-hand side, which is being discussed here, plays no role in proofs of non-existence.

The right-hand side of a CNAME will be chased unless the QTYPE is CNAME, so yes, proofs are in scope because if the right-hand side is a wildcard and is queried as such, fewer RRs need to go on the wire.

**Comment by peterthomassen** [comment]
I'd like to understand more from the original poster.

@renne I would like to get some clarification on the purpose of your original question. This was your example:

```
_DMARC  3600  IN  CNAME  _DMARC.example.org.
*.udp   3600  IN  CNAME  *.tcp.example.org.
```

Let's also assume there are two records in `example.org`:

```
some-name.tcp   3600  IN  A  1.2.3.4
*.tcp           3600  IN  A  9.8.7.6
```

When resolving `some-name.udp` in the original zone via the CNAME, then what would you expect that query to resolve to?

I am asking this because the `some-name` part of the subdomain will _not_ be transferred into the subsequent query under the CNAMEs target, and the resolution will end at the literal `*.tcp` record which yields 9.8.7.6. You cannot use the CNAME wildcard target construction to transfer the query subdomain to the CNAME target: "wildcard propagation" is not happening, and the resolution will not arrive at `some-name.tcp`. (An NS record would do that job.)

My worry is that if we accept wildcards as the CNAME target, users may mistakenly try to set up such unsuited CNAMEs. This is an easy misconception to make, because the meaning of wildcard on the left-hand side (matching) and the right-hand side (literal) is different.

@andrewtj Note that our API _does_ allow setting a wildcard name as the CNAME target. Only the GUI has the limitation, in order to avoid the previously explained misconception. Taking that into account, the question about the GUI use case still stands.

**Comment by andrewtj** [comment]
> @andrewtj Note that our API *does* allow setting a wildcard name as the CNAME target. Only the GUI has the limitation, in order to avoid the previously explained misconception. Taking that into account, the question about the GUI use case still stands.

I understand what you're aiming for but this is not an approach I can get behind. I'll bow out here and leave you to it.

**Comment by peterthomassen** [comment]
@renne Feel free to add clarification for your use case even after closing the issue.
