### ISSUE TITLE
README outdated.

### ISSUE THREAD

**Issue by Leopere** [desec-io/desec-stack#477]
```markdown
Then, copy ca.crt, server.crt, and server.key to openvpn-server/secrets/.
```

Creating server.crt based on the instructions referenced in the README.md does not result in the creation of more than just the one file `ca.crt` it seems that `server.crt` and `server.key` do not exist.

```bash
➜  easyrsa3.ca git:(master) ✗ ls -lAh ./*/*
-rw------- 1 root root 1.2K Nov 19 00:33 ./pki/ca.crt
-rw------- 1 root root    0 Nov 19 00:33 ./pki/index.txt
-rw------- 1 root root    0 Nov 19 00:33 ./pki/index.txt.attr
-rw------- 1 root root 4.6K Nov 19 00:33 ./pki/openssl-easyrsa.cnf
-rw------- 1 root root 4.6K Nov 19 00:33 ./pki/safessl-easyrsa.cnf
-rw------- 1 root root    3 Nov 19 00:33 ./pki/serial
-rw-r--r-- 1 root root  300 Nov 19 00:33 ./x509-types/COMMON
-rw-r--r-- 1 root root  426 Nov 19 00:33 ./x509-types/ca
-rw-r--r-- 1 root root  192 Nov 19 00:33 ./x509-types/client
-rw-r--r-- 1 root root  193 Nov 19 00:33 ./x509-types/code-signing
-rw-r--r-- 1 root root  225 Nov 19 00:33 ./x509-types/email
-rw-r--r-- 1 root root  661 Nov 19 00:33 ./x509-types/kdc
-rw-r--r-- 1 root root  208 Nov 19 00:33 ./x509-types/server
-rw-r--r-- 1 root root  226 Nov 19 00:33 ./x509-types/serverClient

./pki/certs_by_serial:
total 0

./pki/issued:
total 0

./pki/private:
total 4.0K
-rw------- 1 root root 1.8K Nov 19 00:33 ca.key

./pki/renewed:
total 12K
drwx------ 2 root root 4.0K Nov 19 00:33 certs_by_serial
drwx------ 2 root root 4.0K Nov 19 00:33 private_by_serial
drwx------ 2 root root 4.0K Nov 19 00:33 reqs_by_serial

./pki/reqs:
total 0

./pki/revoked:
total 12K
drwx------ 2 root root 4.0K Nov 19 00:33 certs_by_serial
drwx------ 2 root root 4.0K Nov 19 00:33 private_by_serial
drwx------ 2 root root 4.0K Nov 19 00:33 reqs_by_serial
```

The instructions are likely sufficient but they seem unclear so I'd like to remedy this in the documentation by submitting an issue.

**Comment by peterthomassen** [comment]
Thanks for your report! It seems that you only followed the first step of the easy-rsa tutorial that is linked in the README.

In fact, it is necessary to follow all the steps until all required files are created. In the process, `EntityName` needs to be replaced by `server` or `client` (if creating a secondary) so that the files get the right names. Also, for the server deployment, the word `client` in step 4 needs to be replaced by `server` so that the certificate gets the right bits set.

Would you like to try out these steps, and submit a PR to improve the README?

**Comment by Leopere** [comment]
Ran out of time to manage this. Closing my ticket.
