### ISSUE TITLE
Copy & Paste doesn't work in Firefox

### ISSUE THREAD

**Issue by joto** [desec-io/desec-stack#491]
When adding a new domain there is the "info box" which contains the nameservers and keys that need to be copied to the provider. Unfortunately I can't copy and paste them in Firefox (version 78.6.0esr-1~deb10u1). It might be related to some plugins, but copy-and-pasting works fine everywhere else, so it seems desec is doing something "special" here that results in the problem.

I also tested this on Chromium where it works fine.

**Comment by nils-wisiol** [comment]
I can confirm this on Firefox 84 (Ubuntu). When I select the records using the cursor, the selection disappears as soon as I let go of the mouse button.

**Comment by rugk** [comment]
IMHO you should even remove that copying functionality (in the current state), because it does not allow me to select only a part of the shown text. E.g.:
* in some domain name providers I need to enter each NS record one by one (one for each name server). I can, however, only copy both NS's.
* I can also not copy the public key or other parts alone from a DNSKEY, see #502 

BTW, the bug why it does not work may be that you use an async function or somehow else may break the information that the copying API is triggered from a _user event_ (click).
