### ISSUE TITLE
scavenger: do not remove recently touched domains with no changes

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#499]
The domain scavenger currently schedules all domains for deletion, [that haven't recently been *published*](https://github.com/desec-io/desec-stack/blob/master/api/desecapi/management/commands/scavenge-unused.py#L27). ([Also here.](https://github.com/desec-io/desec-stack/blob/master/api/desecapi/management/commands/scavenge-unused.py#L71)) (Curiously, the variable name is *touched*, but the query is on *published*.)

However, an no-op IP update does not trigger an update of the published timestamp on the domain, [as no AXFR is required in that case](https://github.com/desec-io/desec-stack/blob/master/api/desecapi/pdns_change_tracker.py#L273).

This results in the situation that domains are scheduled for deletion even when a user sends regular no-op updates for the domain.

Proposed fix: introduce a touched field on the domain, replacing the Python property, and check against this field. (nb #454 also introduces fields on the domain model, but they are not suitable for this check.)

**Comment by peterthomassen** [comment]
Oops!

The `Domain.touched` property essentially is the maximum of the `touched` fields of all of the domain's RRsets. The same can be achieved in the queryset, by annotating the queryset with a `Max` aggregation, then filtering on it. This is achieved by changing ([here](https://github.com/desec-io/desec-stack/blob/master/api/desecapi/management/commands/scavenge-unused.py#L27))

```python
recently_touched_domains = cls.base_queryset.filter(published__date__gte=last_published_threshold,
                                                    renewal_changed__lt=F('published'))
```

to 

```python
recently_touched_domains = cls.base_queryset.annotate(newest_touched=Max('rrset__touched')) \
    .filter(newest_touched__date__gte=last_published_threshold, renewal_changed__lt=F('newest_touched'))
```

Obviously, the `last_published_threshold` variable should be renamed to `last_touched_threshold` or similar. A similar change would need to be made [also here](https://github.com/desec-io/desec-stack/blob/master/api/desecapi/management/commands/scavenge-unused.py#L71).

Wondering about the query performance, I checked and found that it currently runs in a fraction of a second in production. It probably can be further improved by adding an index on `RRset.touched`, so that `Max` does not require any computations.

Given that, I think this solution should be preferred over adding a (redundant) field on `Domain`.

---

In case the domain has no RRsets (which is a pathological case: the owner would have to remove the NS RRset), the domain will not be selected. Options:
1. do nothing and be ok with that
2. create missing NS in some way, or do something else to get rid of the issue
3. do a little work (with a `Q` object) to check whether the `newest_touched` annotation is `NULL`, and if so, default to `Domain.published`. This should be pretty straightforward and not significantly increase runtime.

I'd be fine with 1. and 3.

**Comment by peterthomassen** [comment]
closed accidentally
