### ISSUE TITLE
api: wildcard domains don't work with IP update API

### ISSUE THREAD

**Issue by Eisfunke** [desec-io/desec-stack#555]
I noticed that the dynDNS/IP update API doesn't accept wildcard domains, I get a `badauth` when trying to specify a wildcard domain as username or `nohost` when specifying as GET parameter.

Skimming through [the code](https://github.com/desec-io/desec-stack/blob/b6f3d47bf4b725cd0547d1087439fcff6118d594/api/desecapi/views.py#L288), I'm not quite sure as to why. Do you think that's fixable? Is it by design? I'd be happy to try and fix it myself if you push me in the right direction.

**Comment by peterthomassen** [comment]
Thanks for the report! The problem is in [`Domain.filter_qname()`](https://github.com/desec-io/desec-stack/blob/b6f3d47bf4b725cd0547d1087439fcff6118d594/api/desecapi/models.py#L211) which applies [Domain name validation](https://github.com/desec-io/desec-stack/blob/b6f3d47bf4b725cd0547d1087439fcff6118d594/api/desecapi/models.py#L198-L204) which is not appropriate here.

Still, some input validation should be done. @nils-wisiol Do you have an idea how to best solve this?

**Comment by peterthomassen** [comment]
I think a good fix is passing `qname.removeprefix('*.')` to the validation call inside `Domain.filter_qname()`, instead of `qname`.

If you'd like to try preparing a fix, that'd be great! Please also extend the `test_identification_by_query_params_with_subdomain` test case accordingly. There's also other functionality that should suffer from the same bug; expanding the test case would help there, too (`test_list_domains_owns_qname`).

**Comment by peterthomassen** [comment]
There's also a test case `test_filter_qname` that should be adjusted. We can also throw in a few invalid examples in `test_filter_qname_invalid`, such as `*.*.example.com`, or `*foo.example.com`, or `foo.*.example.com`.

**Comment by Eisfunke** [comment]
Sounds good, I'll look into it!
