### ISSUE TITLE
FeatureRequest: Limit API Tokens to specific domains

### ISSUE THREAD

**Issue by Fightbackman** [desec-io/desec-stack#572]
Hey,
I am planning to use desec for the management of the dns records for my little side projects.
Now I have the problem that I want to update multiple zones from different servers which I share with friends.
To keep everything more secure I would like to allow them only to update specific domains and not all managed domains.
Is there anything planned for limiting the permissions of tokens to specific domains?
This would be also interesting for dyndns scenarios to allow router to only update the domains they should have access to.

I looked at the existing issues and didn't find anything like this topic. I am no big programmer but would be glad to help making this possible if my entry lever python skills or multiple years of professional ops knowledge could help.

**Comment by peterthomassen** [comment]
Thanks for the suggestion! In fact, we are working on this, see #347 for general considerations and #456 for an implementation draft (scoping per domain and for dynDNS, but not yet for ACME).

Unfortunately due to other work, the PR is not progressing as quickly as I would like, but I think it is coming to a close.
