### ISSUE TITLE
UI is broken for zones with >500 entries

### ISSUE THREAD

**Issue by Brueggus** [desec-io/desec-stack#584]
Zones containing >500 entries are no longer displayed in the UI. The following error message is shown instead: 
> Pagination required. You can query up to 500 items at a time (508 total). Please use the `first` page link (see Link header).

![image](https://user-images.githubusercontent.com/37619/145211538-035341d9-2511-4d6f-8b4b-77aacd6dffe0.png)

I don't know if this is a duplicate of #423, but since this issue breaks the UI, it may make sense to track it in a separate issue.

**Comment by peterthomassen** [comment]
Thanks for the report, that's indeed a known problem.

The difficulty lies in what should be the solution. We can, of course, make the GUI follow the pagination `Link:` headers returned by the server, and offer identical pagination in the GUI.

The problem is that the server-side pagination is always ordered by the RRset's `created` field, so that sorting in the GUI wouldn't work and you wouldn't know on which page to find what record. This server-side limitation is required to ensure consistency for cases where concurrent requests add or even delete RRsets while you're paginating (i.e., if you are on page 3 with RRsets 1001..1500 an done of that range is deleted, the 1501th record will not leak into the third page if you reload with the same pagination link; instead, the "old" page 3 will now contain 499 entries only). If consistency was not ensured, clients iterating of all pages could not be certain not to miss any RRsets or not to encounter duplicates when write operations are going on concurrently.

Worse, the search field at the top would only be able to search through the current page, are pages retrieved so far. Alternatively, the GUI could pre-fetch all pages, but that takes long, is probably a waste of resources on either side, and looks like the user should really be using something like [dnscontrol](https://github.com/StackExchange/dnscontrol).

What are your thoughts on this?

**Comment by Brueggus** [comment]
Those are all valid points and I only see two valid solutions: 

* Either fetch no entries and display a message like "This zone contains too many entries, please use the API instead" or similar. When I encountered the error message in my screenshot for the first time, I was quite concerned that I may have broken the zone somehow. It took me a moment to figure out that the error was related to pagination.
* or fetch all entries, but this may lead to other issues as you pointed out above.

Partial fetching does not make sense imho, since it will lead to incomplete results in searching and sorting.

**Comment by peterthomassen** [comment]
![image](https://user-images.githubusercontent.com/4242683/194189264-de58333d-6729-44a9-8747-27666c1718b6.png)
