### ISSUE TITLE
Vanity nameserver support

### ISSUE THREAD

**Issue by aeternesatiatus** [desec-io/desec-stack#608]
Hi,
I was wondering if vanity nameserver support would be supported one day. Few free DNS hosts do it but one that does it would be nova53.net 
Maybe desec.io could have support for such a thing?

**Comment by nils-wisiol** [comment]
We do not offer this as it makes changing our name server IP addresses harder. Currently, we have 

```
ns1.desec.io 45.54.76.1
ns2.desec.org 157.53.224.1
```

but we do not guarantee that we do not change these addresses. (In fact, we are planning an infrastructure upgrade that would require a change in addresses.)

If you had 

```
ns1.yourcompany.example 45.54.76.1
ns1.yourcompany.exmaple 157.53.224.1
```

and you do not change your records at the same time, your site is broken.

So, offering vanity name server support puts a large logistical effort on infrastructure upgrades, which is why we do not recommend doing that. Are there any important advantages of vanity name servers?

**Comment by mritzmann** [comment]
> Are there any important advantages of vanity name servers?

With vanity nameservers, I can change the nameserver provider without changing the nameserver at the domain registrar. This is useful, for example, if I "manage" the name servers but do not have access to the domain registrar.
