### ISSUE TITLE
Webapp: Pagespeed improvements

### ISSUE THREAD

**Issue by Rotzbua** [desec-io/desec-stack#631]
The pagespeed of the webpage (webapp) could be improved.

## Problem

Currently the reported First Contentful Paint for mobile devices is 10.2 s which is very high.

https://pagespeed.web.dev/report?url=https%3A%2F%2Fdesec.io%2F&form_factor=mobile

## Suggestions by report

* Eliminate render-blocking resources
* Enable text compression
* Reduce unused CSS
* Ensure text remains visible during webfont load

## Comments and possible solutions

Eliminate render-blocking resources:
 * enabling text compression also solves this problem
 * no explicit solution recommendable

Enable text compression:
* can be enabled in the nginx config
* current nginx supports gzip and brotli (better gzip for modern browsers)
* just for for static content, not for API because of security problem BREACH
* biggest impact: **halves the loading time**

Reduce unused CSS: 
* ~90kb by PR #630

Ensure text remains visible during webfont load:
* no action required, because for font can not be improved
* for font `roboto` improvement was done in #626

## Current pagespeed reports
![grafik](https://user-images.githubusercontent.com/7337347/186988381-27924b3e-8baa-485c-9ca3-82b0ef68326f.png)
![grafik](https://user-images.githubusercontent.com/7337347/186988417-b6ae0a26-af22-4afd-867a-3a412b67a442.png)

**Comment by peterthomassen** [comment]
We made a few improvements, in particular adding compression for all static files (unfortunately, the previous deployment only had it enabled for text/html due to nginx config defaults), better webpack chunking, and also client-side caching (doesn't matter on first visit). Metrics from above (which I could reproduce now are):

![image](https://user-images.githubusercontent.com/4242683/194858616-78e6f380-f76e-4ca8-bf3c-bd2f3b71c3a8.png)
![image](https://user-images.githubusercontent.com/4242683/194858806-a088a0a0-85a7-4968-9f57-14675e1a0ef1.png)

We have deployed #630 yet because I'm still torn between whether a tiny wait is a good trade-off for font flickering. So far for the moment.
