### ISSUE TITLE
DS/DNSKEY Info Dialog

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#730]
To improve UI, could look somewhat like this:

![image](https://github.com/desec-io/desec-stack/assets/1026940/5e0a7f11-1153-4cb8-9b71-f4b9f7c7cde9)

**Comment by Valodim** [comment]
Also note that the DS record is sometimes asked with domain name in front, and probably sometimes without although I have no data on that. In the screenshot above, it is also shown with domain in the instructions.

For INWX in particular (which I suspect isn't a small amount of desec users due to its popularity in Germany), from the current interface on desec, the domain name has to be manually prefixed to both DS record lines to make it work. I can easily see folks failing on this.
