### ISSUE TITLE
auth/tokens: wildcard permission should grant permission to create any sub-domain under wildcard

### ISSUE THREAD

**Issue by Atemu** [desec-io/desec-stack#859]
I want each of my hosts to be able to somewhat freely create records inside their hostname "namespace" under `hostname.mydomain.name` but nowhere else in the zone. One of the purposes being acme dns-01 challenges for various services they might be running.

When I gave my token `subname: "hostname"` permission, it is able to create records in `hostname.mydomain.name` as expected. It is not able to create records under it e.g. `_acme-challenge.hostname.mydomain.name` however which is slightly surprising but a valid design decision.  
I then tried to give it `subname: "*.hostname.mydomain.name"` permission and it's indeed able to create the `*.hostname.mydomain.name` record but still not `_acme-challenge.hostname.mydomain.name`. This is very surprising to me as a wildcard theoretically gives it permission to place any sub domain via the wildcard anyways.

I think the wildcard permission on a certain subname should be changed to also allow management of any sub-domain under that subname (perhaps even recursively).

For now I will have to resort to wildcard entries and certs which should be workable for my current use-cases but also not quite what I wanted.

**Comment by peterthomassen** [comment]
Unfortunately, wildcards in the DNS are a complicated topic. The main problem is that wildcards in the DNS are very unintuitively scoped, and it seems questionable whether we should be using wildcard semantics for our API tokens that are different from the DNS scope of wildcards. It seems like this would be inviting misunderstandings, and people granting permissions for things they don't expect to be granted.

In the DNS, a wildcard covers all names on the same level and below *which do not "exist"*. The problem of "existence" is what's so weird. There are at least two implications that one might not expect:

- Often, a administrator might have an IPv6 subnet available, but just one IPv4 address. Thus, for IPv4, one might want to use NAT, but use an IPv6 address that is specific for each hostname. Thus, once could imagine configuring an A record for `*.example.com` and an AAAA record for `something-specific.example.com`. -- However, when querying an A record for `something-specific.example.com`, you will get an empty response, because the name "exists" (due to the AAAA record), so the wildcard does not apply (independently of the type).
- Now consider an A record for `*.example.com` and an AAAA record for `www1.files.example.com`. Note that no record is defined at `files.example.com`, so one might expect the wildcard to apply for this name. However, as the DNS is a tree, and the leaf `www1.files.example.com` exists, the branch leading to that leaf also "exists", even if it doesn't have any records. Such names are called an "empty non-terminal" (ENT). Wildcards don't apply on ENT names.

Now, all of that might sound a bit artificial. But: Do we want to re-create this kind of wildcard scoping for our wildcard subname tokens? If yes, will people understand it? If no, will (some) people make wrong assumptions, thinking that the wildcard token will *only* apply where a corresponding wildcard *record* would apply?

It seems like making this inconsistent might be asking for problems. We've decided that for now, we'll avoid the problem by making the wildcard token apply to the exact wildcard RRset, without any kind of expansion.

if you have any thoughts for how to do something about this without creating dangerous edge cases like the above, we'd love to hear your thoughts. In this case, feel free to reopen this issue.

Meanwhile, you can address your use case by creating a separate zone for `hostname.mydomain.name`, and then creating a token that no subname restriction (`null`). (When creating the domain, don't forget to add a DS record to your parent!)
