### ISSUE TITLE
Security Headers (CORS, CSP)

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#87]
We currently do not allow any cross origin requests on the API, although that may be an important use-case. Implementing such requests however appears to be quite painful, as we must support OPTIONS requests properly to cover CORS preflight requests.

**Comment by asmaps** [comment]
As you are using DRF for the API OPTIONS etc should already be handled properly by that. For the CORS headers I can recommend this package: https://pypi.python.org/pypi/django-cors-headers

**Comment by peterthomassen** [comment]
Another interesting list (for inspiration only): https://github.com/helmetjs/helmet

**Comment by peterthomassen** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by peterthomassen** [comment]
`X-Frame-Options: DENY`

**Comment by peterthomassen** [comment]
https://observatory.mozilla.org/

**Comment by autodiscover** [comment]
For public APIs, [`Access-Control-Allow-Origin: *` is always safe](https://stackoverflow.com/a/43154277/6867099): It's pretty much the same thing as allowing access for `curl`.

When a third-party site wants to make authenticated requests to our API, the inclusion of `Access-Control-Allow-Credentials` is [**not** advised](https://www.sjoerdlangkemper.nl/2018/09/12/authorization-header-and-cors/), as this header [pertains to "credentials mode"](https://fetch.spec.whatwg.org/#http-access-control-allow-credentials) which [means cookies, TLS client certificates, and HTTP authentication with tuples of username/password](https://fetch.spec.whatwg.org/#credentials) (not tokens).

It should suffice to set `Access-Control-Allow-Headers: Authorization` so that third-party pages can set the `Authorization` header. They will have to get the token from the user explicitly. (Using `Access-Control-Allow-Credentials` is more like telling the browser to automatically use any cached credentials it has, and we don't want that.)

When `Access-Control-Allow-Credentials` is not used, `Access-Control-Allow-Origin` can be used with a wildcard value (the `Origin` request header value does not need to be repeated). We can thus probably take care of CORS on the nginx level and set `Access-Control-Allow-Origin: *` statically. However, it may be nicer to use https://pypi.org/project/django-cors-headers/ (thanks, @asmaps!) to get reasonable `Access-Control-Allow-Methods` response header values and such. Let's play around with it and see.

**Comment by autodiscover** [comment]
https://securityheaders.com/?q=desec.io&followRedirects=on

**Comment by autodiscover** [comment]
https://observatory.mozilla.org/analyze/desec.io
