### ISSUE TITLE
CNAME flattening or similar

### ISSUE THREAD

**Issue by fucksophie** [desec-io/desec-stack#916]
Hello, I'd love if desec supported CNAME flattening! Even if only traversing in the current domain or desec-managed domains.

**Comment by peterthomassen** [comment]
What's the use case? Can you give an example of current behavior and proposed behavior?

**Comment by kvdb** [comment]
Would love this feature too. My use case:

We created the [Appsemble](https://gitlab.com/appsemble/appsemble) open source low-code app building platform.
It allows users to connect their domain to the app they've created on the platform.
These are our user instructions for it: https://appsemble.app/en/docs/03-guide/dns

It also notes that you probably need Cloudflare because of the [cname flattering](https://developers.cloudflare.com/dns/cname-flattening/) to get the functionality that we need to get it to work. It'd be great is we can point to deSEC as goto DNS provider instead of CF.

Perhaps we don't understand enough from DNS to realize that there's another way, but as it stands currently, we also need this feature (because we're also users of our own platform).

**Comment by peterthomassen** [comment]
If you mean flattening at the apex (empty subdomain), that's not something we're going to do. For an explanation, see https://talk.desec.io/t/clarification-on-alias-records/113/2.

**Comment by kvdb** [comment]
Thanks for the links. Seems like the `[HTTPS](https://www.netmeister.org/blog/https-rrs.html)` might be the proper way to do accomplish it?

**Comment by peterthomassen** [comment]
Yes, but support is not universal.
