### ISSUE TITLE
api: create domain fails

### ISSUE THREAD

**Issue by gerhard-tinned** [desec-io/desec-stack#92]
The api allows creation ofa domain. Accroding to the documentation, the /api/v1/domains/ endpoint should be used together with the API tocken as header and the "name" field as the only post variable. 

```
*** DEBUG: http-request : http-url    : https://desec.io/api/v1/domains/
*** DEBUG: http-request : http-type   : POST
*** DEBUG: http-request : http-header : {'Authorization': 'Token 123apitocken456'}
*** DEBUG: http-request : http-data   : {"name": "example.com"}
*** DEBUG: http-response: http-code   : 400
*** DEBUG: http-response: http-error  : '400: Bad Request'
*** DEBUG: http-response: http-body   :
{"name":["This field is required."]}

Error: The request failed with 400: Bad Request
```

The api returns a "400 Bad Request" return code and as returned content a hint about the "name" field beeing required. As the "name feeld was added in the request, I suspect a bug in the api.

**Comment by peterthomassen** [comment]
Thanks for the report. Can you please post the code you are using to send this request?

**Comment by gerhard-tinned** [comment]
I will publish the script soon ... repo is already prepared. I hope to publish it today or tomorrow.

https://github.com/gerhard-tinned/desec-dns-api-cli

**Comment by peterthomassen** [comment]
Nice! :+1: 

Your method `deSEC_DNS_API.domain_create()` sends the headers set in `self.header` which has the value `{'Authorization': 'Token ' + api_token}`. For the JSON payload to be accepted on the server side, it is necessary to also send a `Content-Type: application/json` header as well. Otherwise, since the content type is undefined, the server does not know how to parse the request, and the `name` field is not found.

You're doing the right thing in `rrset_create()` and `rrset_modify()`, but in fact it needs to be done for every request that has a JSON payload. Once you change that, things should work.

**Comment by gerhard-tinned** [comment]
Thanks. fixed it. The script now supports all features. :)
