### ISSUE TITLE
Download all zone files as .zip

### ISSUE THREAD

**Issue by AbelLykens** [desec-io/desec-stack#987]
Hi there! 

I very much like the advanced feature to download zone files. 

Even more useful would be an option to download ALL zone files as a zip.

Thanks for reading my request 😄

**Comment by peterthomassen** [comment]
This would add extra complexity / dependencies for zipping on the backend; that's not necessary, however, because one can just iterate through domains and download the zonefiles with a simple script. We prefer to have the additional complexity to be on the client side.

Further, this would either be a circumvention to our rate limit mechanism, or we would have to count each zip download as several requests, which does not fit the request processing flow.
