### ISSUE TITLE
Add curl examples to docs

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#99]
Currently, the docs are split into curl and httpie examples. We should find a way to support both.

**Comment by My1** [comment]
I totally agree. curl would be nice.

especially since curl makes many things a lot more obvious than the HTTPie examples do, because HTTPie assumes and basically autofill a lot.

by the way, I am (albeit very slowly) working on examples that show the Plain HTTP side of things so users can see it in a totally framework-agnostic way, that doesnt imply ANYTHING

https://github.com/My1/desec-http-docs
